### ISSUE TITLE
Resetting filter redirect to url with wrong get parameters query 

### ISSUE THREAD

**Issue by ardianys** [leikind/wice_grid#152]
Thanks for this wonderful gem, but currently I have an error.
My step that produce error :
- I filtering in some column 
- I reset it using reset button provided automatically by wicegrid
- it redirect to `http://0.0.0.0:3000/downloads/my?grid=`
- and rails render
  ![download](https://cloud.githubusercontent.com/assets/196382/3008071/aa797bc2-deac-11e3-88b4-629214a7261b.jpg)

But I can ensure that when I add some column ordering, wicegrid can reset the grid without errors. My step that work :
- I filtering in some column 
- I ordering some column (or vice versa with number 1)
- I reset it using reset button provided automatically by wicegrid
- it redirect to `http://0.0.0.0:3000/downloads/my?grid%5Border%5D=id&grid%5Border_direction%5D=asc`
- although I hope it can be redirected to 'http://0.0.0.0:3000/downloads/my` without any trailing query
- and rails work

I have search in this github or google but I can't find it out.

**Comment by leikind** [comment]
A stacktrace would be nice

**Comment by ardianys** [comment]
Here it's.
Thanks.

``` ruby
TypeError in DownloadsController#my
no implicit conversion of Symbol into Integer

Extracted source (around line #11):

9
10 def my
11  @downloads_grid = initialize_grid(
12  Download
13  # .where(user: current_user)
14 )

Rails.root: /home/abdul/rails/audiosalaf

Full Trace
wice_grid (3.4.2) lib/wice_grid.rb:175:in `[]'
wice_grid (3.4.2) lib/wice_grid.rb:175:in `process_loading_query'
wice_grid (3.4.2) lib/wice_grid.rb:153:in `initialize'
wice_grid (3.4.2) lib/wice/wice_grid_controller.rb:70:in `new'
wice_grid (3.4.2) lib/wice/wice_grid_controller.rb:70:in `initialize_grid'
app/controllers/downloads_controller.rb:11:in `my'
actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:676:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.0) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.0) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.0) lib/rails/engine.rb:514:in `call'
railties (4.1.0) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/abdul/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/abdul/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/home/abdul/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by leikind** [comment]
Please add `p params` before `@downloads_grid = initialize_grid ...` and post its contents right before the crash

**Comment by ardianys** [comment]
I'm sorry I'm newbie in RoR,
Did you mean like this `{"grid"=>"", "action"=>"my", "controller"=>"downloads"}` ?

``` ruby
Started GET "/download/my?grid=" for 127.0.0.1 at 2014-05-19 06:23:34 +0700
Processing by DownloadsController#my as HTML
  Parameters: {"grid"=>""}
{"grid"=>"", "action"=>"my", "controller"=>"downloads"}
Completed 500 Internal Server Error in 2ms

TypeError (no implicit conversion of Symbol into Integer):
  app/controllers/downloads_controller.rb:12:in `my'


  Rendered /home/abdul/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.8ms)
  Rendered /home/abdul/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.4ms)
  Rendered /home/abdul/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (6.7ms)
  Rendered /home/abdul/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (45.5ms)
```

**Comment by ardianys** [comment]
I'll try to provide complete javascript debug in next hours, it seems that it's related with js.
But here it's some of them.
![screenshot from 2014-05-19 06 47 01](https://cloud.githubusercontent.com/assets/196382/3009112/f3526d9c-dee6-11e3-9689-7ee924576600.png)
![screenshot from 2014-05-19 06 46 42](https://cloud.githubusercontent.com/assets/196382/3009113/f3595670-dee6-11e3-9dd8-5a82df786094.png)
![screenshot from 2014-05-19 06 45 48](https://cloud.githubusercontent.com/assets/196382/3009114/f35de96a-dee6-11e3-8047-4fcedee0e6f5.png)

**Comment by ardianys** [comment]
Hi, I tried to follow your code. Here it's my result, CMIIW.
The problem isn't from javascript, javascript just redirecting the page to defined `base_link_for_filter` which defined in `div` after `</table>` element.
The exact problem is from `base_link_for_filter` definition inside your ruby code.

``` ruby
base_link_with_pp_info = controller.url_for(new_params).gsub(/\?+$/,'')
```

but new_params value are

```
(byebug) p new_params
{"grid"=>{}, "action"=>"my", "controller"=>"downloads", "only_path"=>false}
```

So I add one line code to remove this @grid.name value like this

```
new_params.except!(@grid.name)
```

And now my grid working nicely.
I have put this to PR for your review.
Please note that I didn't know yet full app flow, but if my update is correct, I'm very happy if it can be merged.
Thanks.

**Comment by ardianys** [comment]
Oh dear,
My code was already done in this commit
https://github.com/leikind/wice_grid/commit/127b51a0a981cb74ef13d6e3a3b02c301c4c20f2
