### ISSUE TITLE
DateTimePicker seems to be wrong

### ISSUE THREAD

**Issue by Allen-Li** [leikind/wice_grid#293]
I used  the following code，but the DateTimePicker position was wrong，and invalid click，when i double-click on DateTimePicker, it was gone wrong.

``` ruby
g.column name: 'Created', attribute: 'created_at'
```

Error message

``` javascript
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'left' of undefined
    at getSelectionEndPosition (chrome-extension://eopjamdnofihpioajgfdikhhbobonhbb/lookup.js:90:21)
    at createPopUp (chrome-extension://eopjamdnofihpioajgfdikhhbobonhbb/lookup.js:689:32)
    at createPopUpEx (chrome-extension://eopjamdnofihpioajgfdikhhbobonhbb/lookup.js:653:4)
    at onText (chrome-extension://eopjamdnofihpioajgfdikhhbobonhbb/lookup.js:844:2)
```

Could anyone help me? thx.

**Comment by leikind** [comment]
Your error is in some Chrome extension. What does WiceGrid have to do with this?
